import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#5e4117",
        "inverse-surface": "#2f3033",
        "on-surface-variant": "#43474d",
        "on-primary-fixed": "#001d34",
        "on-surface": "#1a1c1e",
        "surface-tint": "#46617d",
        "on-secondary-fixed-variant": "#454749",
        "on-error": "#ffffff",
        "secondary-container": "#e2e2e5",
        "inverse-on-surface": "#f1f0f3",
        "surface-container-low": "#f4f3f6",
        "on-secondary-fixed": "#1a1c1e",
        secondary: "#5d5e61",
        "on-tertiary-fixed": "#291800",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#2e4964",
        "surface-dim": "#dadadc",
        "on-primary-container": "#28435e",
        "outline-variant": "#c3c7ce",
        "primary-fixed": "#d0e4ff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#e2e2e5",
        outline: "#73777e",
        "secondary-fixed-dim": "#c6c6c9",
        "on-secondary": "#ffffff",
        primary: "#46617d",
        error: "#ba1a1a",
        "surface-container": "#eeedf0",
        surface: "#faf9fc",
        "primary-container": "#95b0d0",
        "on-primary": "#ffffff",
        "tertiary-container": "#cfa773",
        "surface-container-highest": "#e3e2e5",
        tertiary: "#78582c",
        "tertiary-fixed": "#ffddb4",
        background: "#faf9fc",
        "surface-variant": "#e3e2e5",
        "surface-container-high": "#e8e8eb",
        "primary-fixed-dim": "#aec9ea",
        "on-tertiary-container": "#583c12",
        "on-error-container": "#93000a",
        "surface-bright": "#faf9fc",
        "on-background": "#1a1c1e",
        "inverse-primary": "#aec9ea",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#eabf89",
        "on-secondary-container": "#636467",
      },
      fontFamily: {
        headline: ["var(--font-noto-serif)", "serif"],
        body: ["var(--font-manrope)", "sans-serif"],
        label: ["var(--font-manrope)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
